### ISSUE TITLE
Changes to the footer links to include other pages not included in the header

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-landing-page#10]
The friends page; https://www.openvoiceos.org/friends

Is only accesable by clicking the link on the about page.

To increase findability of those type of pages, isn't it qan idea to include them in the footer which is now basically a copy of the top menu.

**Comment by suvanbanerjee** [comment]
Sure adding a sitemap.xml file and links in footer is a good idea

**Comment by JarbasAl** [comment]
was about to open an issue but noticed this one existed

![image](https://github.com/user-attachments/assets/c5d3f870-a61d-46d1-aff0-41dae1fba536)
