### ISSUE TITLE
Draft: Add contributing page

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-landing-page#9]
Users, developers or any other interested person or organization/ company can help us out via different methods. The below is to gather ideas and the required infromation to add into a "contributing" page or section.

I like the below blocks and would like similar blocks for the different contributing methods;
![image](https://github.com/user-attachments/assets/06e45ad5-8547-4140-8ac9-fc8916bd52ce)

Below how the page could look like. First a bit of introductional text, followed by the different blocks underneath.

---

# How you can help
OpenVoiceOS is an open-source voice assistant platform powered by a passionate community of developers, translators, testers, and advocates. Whether you're skilled in coding, translation, testing, documentation, or simply spreading the word, your contributions are vital to our mission of creating a customizable, privacy-focused, and inclusive voice assistant. We're also grateful for financial donations, which help sustain the project's growth and innovation. No matter how you choose to contribute, your involvement helps make OpenVoiceOS a powerful, adaptable, and accessible tool for users around the world.

## Coding
OpenVoiceOS, is always actively seeking contributions from developers across its entire framework. Whether you're skilled in front-end interfaces, backend services, machine learning, or voice recognition, your expertise can help advance this community-driven project. Developers can contribute by improving existing features, fixing bugs, or optimizing performance, ensuring the platform remains robust, user-friendly, and accessible to a broader audience.

## Building a skill and/ or plugin
We welcome developers who can create skills and plugins to help expand its functionality and versatility. By contributing your creativity with coding new skills, enhance existing ones, or develop new plugins that integrate seamlessly with the platform we enrich the user experience and offering more personalized and diverse interactions.

## Helping with translation
OpenVoiceOS is committed to ensuring that no language is left behind and is seeking help from translators around the globe to make this vision a reality. As an open-source voice assistant platform, OpenVoiceOS aims to be accessible to users around the world, regardless of their native language.

## Testing & Quality Assurance
The easiest way to contribute is most likely by just user, test and report back any issues found for quality assurance. This helps to maintain the platform's reliability and performance, ensuring that the voice assistant functions work seamlessly across various devices and scenarios whic is crucial for delivering a top-notch user experience. Identifying and resolve bugs, improve system stability, and ensure that new features are implemented smoothly.

## Documentation
OpenVoiceOS is seeking contributors to help enhance both user and developer documentation, a critical aspect of making the platform accessible and easy to use. Clear, comprehensive documentation is essential for guiding users through the setup and operation of the voice assistant, as well as for assisting developers in creating new features, skills, and plugins. Whether you're skilled in writing, technical communication, or have a deep understanding of OpenVoiceOS, your contributions can ensure that documentation is thorough, up-to-date, and user-friendly.

## Sharing is Caring
We are looking for passionate advocates to help spread the word. By raising awareness through social media, blogs, community forums, and other channels, you can play a crucial role in growing the OpenVoiceOS community. Whether you enjoy creating content, engaging with tech enthusiasts, or networking within developer circles, your efforts can help attract more users and contributors to the project.

## Donating
OpenVoiceOS welcomes support in the form of donations to help sustain and grow its open-source voice assistant platform. Donations play a vital role in covering essential expenses, such as server costs, development tools, and other resources that keep the project running smoothly. By contributing financially, you can directly impact the platform's ability to innovate, improve, and remain accessible to everyone. Whether it's a one-time donation or ongoing support, every contribution helps ensure that OpenVoiceOS continues to thrive as a community-driven project

**Comment by j1nx** [comment]
We also still have this; https://github.com/OpenVoiceOS/.github/blob/main/CONTRIBUTING.md

However no clue how to click towards that page from anywhere?

**Comment by j1nx** [comment]
Updated the first post with my vission of the content.

**Comment by suvanbanerjee** [comment]
@j1nx, please provide URLs for the `Know More` buttons. We also need to determine how to integrate this page—perhaps by adding it to the header or incorporating it somewhere on the homepage.
